apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name}}-virtual-service
  namespace: {{ .Values.namespace.name}}
spec:
  hosts:
  - "futakai.com"
  gateways:
  - istio-system/istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /contents

    route:
    - destination:
        host: futakai-contents-service.futakai-fe.svc.cluster.local
        port:
          number:  {{ .Values.ports.port}}




